[package]
name = "pgshell"
version = "0.1.0"
authors = ["Damien Ayers <damien@omad.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "7.0.0"
postgres = "0.18.1"
